// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proiect_PSSC.Data;

#nullable disable

namespace Proiect_PSSC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251209150321_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Entities.DeliveredOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CustomerId");

                    b.Property<DateTime>("DeliveredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeliveredAt");

                    b.Property<string>("DeliverySignature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DeliverySignature");

                    b.Property<DateTime>("PreparedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("PreparedAt");

                    b.Property<string>("ReservationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ReservationId");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ReservedAt");

                    b.Property<string>("WarehouseLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("WarehouseLocation");

                    b.HasKey("Id");

                    b.ToTable("DeliveredOrders", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Entities.DeliveredShipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Carrier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Carrier");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CustomerId");

                    b.Property<DateTime>("DeliveredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeliveredAt");

                    b.Property<string>("DeliverySignature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DeliverySignature");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OrderId");

                    b.Property<DateTime>("PreparedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("PreparedAt");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RecipientName");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrackingNumber");

                    b.HasKey("Id");

                    b.ToTable("DeliveredShipments", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Entities.SentInvoice", b =>
                {
                    b.Property<string>("InvoiceId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("InvoiceId");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CustomerId");

                    b.Property<string>("DeliveryMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DeliveryMethod");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("GeneratedAt");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("InvoiceNumber");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OrderId");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("SentAt");

                    b.Property<string>("SentTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SentTo");

                    b.HasKey("InvoiceId");

                    b.ToTable("SentInvoices", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Entities.DeliveredOrder", b =>
                {
                    b.OwnsOne("Domain.Models.ValueObjects.Address", "DeliveryAddress", b1 =>
                        {
                            b1.Property<int>("DeliveredOrderId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PostalCode");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Street");

                            b1.HasKey("DeliveredOrderId");

                            b1.ToTable("DeliveredOrders");

                            b1.WithOwner()
                                .HasForeignKey("DeliveredOrderId");
                        });

                    b.OwnsOne("Domain.Models.ValueObjects.Money", "TotalAmount", b1 =>
                        {
                            b1.Property<int>("DeliveredOrderId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TotalAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Currency");

                            b1.HasKey("DeliveredOrderId");

                            b1.ToTable("DeliveredOrders");

                            b1.WithOwner()
                                .HasForeignKey("DeliveredOrderId");
                        });

                    b.OwnsMany("Domain.Models.Entities.OrderItem", "Items", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("DeliveredOrderId")
                                .HasColumnType("int");

                            b1.Property<string>("ProductId")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProductId");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int")
                                .HasColumnName("Quantity");

                            b1.HasKey("Id");

                            b1.HasIndex("DeliveredOrderId");

                            b1.ToTable("OrderItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DeliveredOrderId");

                            b1.OwnsOne("Domain.Models.ValueObjects.Money", "UnitPrice", b2 =>
                                {
                                    b2.Property<int>("OrderItemId")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("UnitPriceAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("UnitPriceCurrency");

                                    b2.HasKey("OrderItemId");

                                    b2.ToTable("OrderItems");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderItemId");
                                });

                            b1.Navigation("UnitPrice")
                                .IsRequired();
                        });

                    b.Navigation("DeliveryAddress")
                        .IsRequired();

                    b.Navigation("Items");

                    b.Navigation("TotalAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Entities.DeliveredShipment", b =>
                {
                    b.OwnsOne("Domain.Models.ValueObjects.Address", "DeliveryAddress", b1 =>
                        {
                            b1.Property<int>("DeliveredShipmentId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PostalCode");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Street");

                            b1.HasKey("DeliveredShipmentId");

                            b1.ToTable("DeliveredShipments");

                            b1.WithOwner()
                                .HasForeignKey("DeliveredShipmentId");
                        });

                    b.OwnsMany("Domain.Models.Entities.ShipmentItem", "Items", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("DeliveredShipmentId")
                                .HasColumnType("int");

                            b1.Property<string>("ProductId")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProductId");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int")
                                .HasColumnName("Quantity");

                            b1.HasKey("Id");

                            b1.HasIndex("DeliveredShipmentId");

                            b1.ToTable("ShipmentItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DeliveredShipmentId");
                        });

                    b.Navigation("DeliveryAddress")
                        .IsRequired();

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Domain.Models.Entities.SentInvoice", b =>
                {
                    b.OwnsMany("Domain.Models.Entities.InvoiceItem", "Items", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("ProductId")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProductId");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int")
                                .HasColumnName("Quantity");

                            b1.Property<string>("SentInvoiceId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("Id");

                            b1.HasIndex("SentInvoiceId");

                            b1.ToTable("InvoiceItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SentInvoiceId");

                            b1.OwnsOne("Domain.Models.ValueObjects.Money", "LineTotal", b2 =>
                                {
                                    b2.Property<int>("InvoiceItemId")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("LineTotalAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("LineTotalCurrency");

                                    b2.HasKey("InvoiceItemId");

                                    b2.ToTable("InvoiceItems");

                                    b2.WithOwner()
                                        .HasForeignKey("InvoiceItemId");
                                });

                            b1.OwnsOne("Domain.Models.ValueObjects.Money", "UnitPrice", b2 =>
                                {
                                    b2.Property<int>("InvoiceItemId")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("UnitPriceAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("UnitPriceCurrency");

                                    b2.HasKey("InvoiceItemId");

                                    b2.ToTable("InvoiceItems");

                                    b2.WithOwner()
                                        .HasForeignKey("InvoiceItemId");
                                });

                            b1.Navigation("LineTotal")
                                .IsRequired();

                            b1.Navigation("UnitPrice")
                                .IsRequired();
                        });

                    b.OwnsOne("Domain.Models.ValueObjects.Address", "BillingAddress", b1 =>
                        {
                            b1.Property<string>("SentInvoiceInvoiceId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PostalCode");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Street");

                            b1.HasKey("SentInvoiceInvoiceId");

                            b1.ToTable("SentInvoices");

                            b1.WithOwner()
                                .HasForeignKey("SentInvoiceInvoiceId");
                        });

                    b.OwnsOne("Domain.Models.ValueObjects.Money", "TotalAmount", b1 =>
                        {
                            b1.Property<string>("SentInvoiceInvoiceId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TotalAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Currency");

                            b1.HasKey("SentInvoiceInvoiceId");

                            b1.ToTable("SentInvoices");

                            b1.WithOwner()
                                .HasForeignKey("SentInvoiceInvoiceId");
                        });

                    b.Navigation("BillingAddress")
                        .IsRequired();

                    b.Navigation("Items");

                    b.Navigation("TotalAmount")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
